#!/bin/bash

default_profile=$(plutil -p /Users/$(whoami)/Library/Preferences/com.apple.Terminal.plist | grep "Default Window Settings" | tr -d '"' | cut -f2 -d '>' | xargs)
if [[ "$default_profile" = "Basic" ]]; then osascript -e 'tell application "Terminal" to  set current settings of window 1 to settings set "Ocean"'; fi

clear && printf '\e[3J' && printf '\033[0;0H'

if [[ ! -f ~/Library/Application\ Support/AppleGVADetector/debug_on.txt ]]; then rm -f ~/Library/Application\ Support/AppleGVADetector/debug_on.txt; fi

gva_debug=$( defaults read com.apple.AppleGVA enableSyslog 2>/dev/null )
if [[ ! $gva_debug = 1 ]]; then defaults write com.apple.AppleGVA enableSyslog -boolean true
    else 
        if [[ ! -d ~/Library/Application\ Support/AppleGVADetector ]]; then mkdir  ~/Library/Application\ Support/AppleGVADetector; fi
        touch ~/Library/Application\ Support/AppleGVADetector/debug_on.txt
 fi

log stream --style compact --predicate 'eventMessage CONTAINS "GVA"'

exit
